version: '3'

services: 
    app:
        build:
            dockerfile: Dockerfile
            args: 
                VARIANT: 11
                INSTALL_MAVEN: 'true'
                INSTALL_NODE: 'true'
            context: .
        ports:
            - 8080:8080
        volumes: 
            - ../:/app
        command: tail -f /dev/null
    db:
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mallorcaworks
    